name: master

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build Project & Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_ACCOUNT_KEY }}'

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          overwrite-settings: false
          cache: maven

      - name: Maven Build & Tests
        run: mvn --batch-mode --no-transfer-progress -U clean verify package

      - name: Maven deploy
        run:  mvn deploy